### ISSUE TITLE
Failed to push to GCR

### ISSUE THREAD

**Issue by minimum2scp** [groovenauts/brocket#17]
With brocket v0.2.3 (#16), succeeded to push image to Docker Hub, but failed to push image to GCR.

### Docker Hub

Dockerfile:

```
# [config] IMAGE_NAME: "sample_app"
# [config]
# [config] GIT_TAG_PREFIX: "sample_app/"
# [config]
# [config] DOCKER_PUSH_USERNAME: "minimum2scp"
# [config] DOCKER_PUSH_EXTRA_TAG: "latest"
# [config]
# [config] WORKING_DIR: "."
# [config]

(snip)
```

`brocket docker push` succeeded.

```console
tsuyoshi@mira% brocket docker push
I, [2017-05-19T15:12:42.917503 #20739]  INFO -- : [docker push] starting
I, [2017-05-19T15:12:42.933246 #20739]  INFO -- : executing: docker tag sample_app:0.1.0 minimum2scp/sample_app:0.1.0 && docker tag sample_app:0.1.0 minimum2scp/sample_app:latest && docker push minimum2scp/sample_app:0.1.0 && docker push minimum2scp/sample_app:latest 2>&1
D, [2017-05-19T15:12:43.023388 #20739] DEBUG -- : The push refers to a repository [docker.io/minimum2scp/sample_app]
(snip)
D, [2017-05-19T15:12:56.962690 #20739] DEBUG -- : latest: digest: sha256:b437a3771bf3c56f2b596c27255783e108449ee232aafeb3ef536ff8ee510540 size: 3470
I, [2017-05-19T15:12:56.964111 #20739]  INFO -- : SUCCESS: docker tag sample_app:0.1.0 minimum2scp/sample_app:0.1.0 && docker tag sample_app:0.1.0 minimum2scp/sample_app:latest && docker push minimum2scp/sample_app:0.1.0 && docker push minimum2scp/sample_app:latest 2>&1
I, [2017-05-19T15:12:56.964164 #20739]  INFO -- : [docker push] OK
```

### GCR

Dockerfile:
```
# [config] IMAGE_NAME: "sample_app"
# [config]
# [config] GIT_TAG_PREFIX: "sample_app/"
# [config]
# [config] DOCKER_PUSH_COMMAND: "gcloud docker push"
# [config] DOCKER_PUSH_REGISTRY: "gcr.io"
# [config] DOCKER_PUSH_USERNAME: "gke-example-20170514"
# [config] DOCKER_PUSH_EXTRA_TAG: "latest"
# [config]
# [config] WORKING_DIR: "."
# [config]

(snip)
```

`brocket docker push` **failed** with error message `ERROR: (gcloud.docker) unrecognized arguments: push`.

```console
tsuyoshi@mira% brocket docker push
I, [2017-05-19T15:14:15.021369 #20897]  INFO -- : [docker push] starting
I, [2017-05-19T15:14:15.037101 #20897]  INFO -- : executing: docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:0.1.0 && docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:latest && gcloud docker push gcr.io/gke-example-20170514/sample_app:0.1.0 && gcloud docker push gcr.io/gke-example-20170514/sample_app:latest 2>&1
ERROR: (gcloud.docker) unrecognized arguments:
  push
  gcr.io/gke-example-20170514/sample_app:0.1.0
E, [2017-05-19T15:14:15.334317 #20897] ERROR -- : FAILURE: docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:0.1.0 && docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:latest && gcloud docker push gcr.io/gke-example-20170514/sample_app:0.1.0 && gcloud docker push gcr.io/gke-example-20170514/sample_app:latest 2>&1
[LoggerPipe::Failure] FAILURE: docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:0.1.0 && docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:latest && gcloud docker push gcr.io/gke-example-20170514/sample_app:0.1.0 && gcloud docker push gcr.io/gke-example-20170514/sample_app:latest 2>&1
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/logger_pipe-0.3.1/lib/logger_pipe/runner.rb:57:in `block (2 levels) in execute'
  /usr/lib/ruby/2.3.0/timeout.rb:74:in `timeout'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/logger_pipe-0.3.1/lib/logger_pipe/runner.rb:66:in `timeout'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/logger_pipe-0.3.1/lib/logger_pipe/runner.rb:41:in `block in execute'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/logger_pipe-0.3.1/lib/logger_pipe/runner.rb:111:in `setup'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/logger_pipe-0.3.1/lib/logger_pipe/runner.rb:38:in `execute'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/logger_pipe-0.3.1/lib/logger_pipe.rb:18:in `run'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/brocket-0.2.3/lib/brocket/base.rb:47:in `sh'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/brocket-0.2.3/lib/brocket/docker.rb:38:in `push'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/tsuyoshi/.gem/ruby/2.3.0/gems/brocket-0.2.3/bin/brocket:6:in `<top (required)>'
  /home/tsuyoshi/.gem/ruby/2.3.0/bin/brocket:22:in `load'
  /home/tsuyoshi/.gem/ruby/2.3.0/bin/brocket:22:in `<main>'
```

**Comment by minimum2scp** [comment]
`--` is required between `gcloud docker` and `push`.

```console
tsuyoshi@mira% gcloud docker push gcr.io/gke-example-20170514/sample_app:latest
ERROR: (gcloud.docker) unrecognized arguments:
  push
  gcr.io/gke-example-20170514/sample_app:latest
tsuyoshi@mira% gcloud docker -- push gcr.io/gke-example-20170514/sample_app:latest
The push refers to a repository [gcr.io/gke-example-20170514/sample_app]
67f9fc3d4203: Pushed 
07a3a0d30832: Pushed 
d6eac34e91b5: Pushed 
3b20fdaa9c77: Pushed 
7a668240bf6a: Pushed 
fd9c076fbb49: Pushed 
07e51e3f80de: Pushed 
8e6133f6d26b: Pushed 
fd8cb2d9bb24: Pushed 
7e0b138fec00: Pushed 
ac45884e47e6: Pushed 
f078de0e3e2b: Layer already exists 
e6562eb04a92: Layer already exists 
596280599f68: Layer already exists 
5d6cbe0dbcf9: Layer already exists 
latest: digest: sha256:608557702901a6eb7403e2a5d86540877337df4051c93c4b58c452cd0aa3a8f0 size: 3470
```

**Comment by minimum2scp** [comment]
Modify Dockerfile like this

```diff
diff --git a/sample_app/Dockerfile b/sample_app/Dockerfile
index e6409ff..fde1c66 100644
--- a/sample_app/Dockerfile
+++ b/sample_app/Dockerfile
@@ -2,7 +2,7 @@
 # [config]
 # [config] GIT_TAG_PREFIX: "sample_app/"
 # [config]
-# [config] DOCKER_PUSH_COMMAND: "gcloud docker push"
+# [config] DOCKER_PUSH_COMMAND: "gcloud docker -- push"
 # [config] DOCKER_PUSH_REGISTRY: "gcr.io"
 # [config] DOCKER_PUSH_USERNAME: "gke-example-20170514"
 # [config] DOCKER_PUSH_EXTRA_TAG: "latest"
```

and then `brocket docker push` succeeeded.

```console
tsuyoshi@mira% brocket docker push
I, [2017-05-19T15:35:26.450545 #23780]  INFO -- : [docker push] starting
I, [2017-05-19T15:35:26.466426 #23780]  INFO -- : executing: docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:0.1.0 && docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:latest && gcloud docker -- push gcr.io/gke-example-20170514/sample_app:0.1.0 && gcloud docker -- push gcr.io/gke-example-20170514/sample_app:latest 2>&1
D, [2017-05-19T15:35:27.180484 #23780] DEBUG -- : The push refers to a repository [gcr.io/gke-example-20170514/sample_app]
D, [2017-05-19T15:35:27.354802 #23780] DEBUG -- : 67f9fc3d4203: Preparing
D, [2017-05-19T15:35:27.354860 #23780] DEBUG -- : 07a3a0d30832: Preparing
D, [2017-05-19T15:35:27.354884 #23780] DEBUG -- : d6eac34e91b5: Preparing
D, [2017-05-19T15:35:27.354915 #23780] DEBUG -- : 3b20fdaa9c77: Preparing
D, [2017-05-19T15:35:27.354953 #23780] DEBUG -- : 7a668240bf6a: Preparing
D, [2017-05-19T15:35:27.354974 #23780] DEBUG -- : fd9c076fbb49: Preparing
D, [2017-05-19T15:35:27.355000 #23780] DEBUG -- : 07e51e3f80de: Preparing
D, [2017-05-19T15:35:27.355042 #23780] DEBUG -- : 8e6133f6d26b: Preparing
D, [2017-05-19T15:35:27.355071 #23780] DEBUG -- : fd8cb2d9bb24: Preparing
D, [2017-05-19T15:35:27.355088 #23780] DEBUG -- : 7e0b138fec00: Preparing
D, [2017-05-19T15:35:27.355105 #23780] DEBUG -- : ac45884e47e6: Preparing
D, [2017-05-19T15:35:27.355122 #23780] DEBUG -- : f078de0e3e2b: Preparing
D, [2017-05-19T15:35:27.355139 #23780] DEBUG -- : e6562eb04a92: Preparing
D, [2017-05-19T15:35:27.355155 #23780] DEBUG -- : 596280599f68: Preparing
D, [2017-05-19T15:35:27.355176 #23780] DEBUG -- : 5d6cbe0dbcf9: Preparing
D, [2017-05-19T15:35:27.355191 #23780] DEBUG -- : 07e51e3f80de: Waiting
D, [2017-05-19T15:35:27.355208 #23780] DEBUG -- : 8e6133f6d26b: Waiting
D, [2017-05-19T15:35:27.355224 #23780] DEBUG -- : fd8cb2d9bb24: Waiting
D, [2017-05-19T15:35:27.355244 #23780] DEBUG -- : 7e0b138fec00: Waiting
D, [2017-05-19T15:35:27.355265 #23780] DEBUG -- : ac45884e47e6: Waiting
D, [2017-05-19T15:35:27.355282 #23780] DEBUG -- : f078de0e3e2b: Waiting
D, [2017-05-19T15:35:27.355961 #23780] DEBUG -- : e6562eb04a92: Waiting
D, [2017-05-19T15:35:27.355989 #23780] DEBUG -- : 596280599f68: Waiting
D, [2017-05-19T15:35:27.356010 #23780] DEBUG -- : 5d6cbe0dbcf9: Waiting
D, [2017-05-19T15:35:27.356027 #23780] DEBUG -- : fd9c076fbb49: Waiting
D, [2017-05-19T15:35:34.855602 #23780] DEBUG -- : 7a668240bf6a: Pushed
D, [2017-05-19T15:35:34.928623 #23780] DEBUG -- : 67f9fc3d4203: Pushed
D, [2017-05-19T15:35:35.202442 #23780] DEBUG -- : 07a3a0d30832: Pushed
D, [2017-05-19T15:35:35.606824 #23780] DEBUG -- : d6eac34e91b5: Pushed
D, [2017-05-19T15:35:41.737978 #23780] DEBUG -- : fd9c076fbb49: Pushed
D, [2017-05-19T15:35:41.930674 #23780] DEBUG -- : 8e6133f6d26b: Pushed
D, [2017-05-19T15:35:43.024460 #23780] DEBUG -- : fd8cb2d9bb24: Pushed
D, [2017-05-19T15:35:43.848027 #23780] DEBUG -- : 3b20fdaa9c77: Pushed
D, [2017-05-19T15:35:44.975921 #23780] DEBUG -- : 07e51e3f80de: Pushed
D, [2017-05-19T15:35:45.040662 #23780] DEBUG -- : f078de0e3e2b: Layer already exists
D, [2017-05-19T15:35:45.830966 #23780] DEBUG -- : e6562eb04a92: Layer already exists
D, [2017-05-19T15:35:46.927461 #23780] DEBUG -- : 596280599f68: Layer already exists
D, [2017-05-19T15:35:47.701014 #23780] DEBUG -- : 5d6cbe0dbcf9: Layer already exists
D, [2017-05-19T15:35:48.924933 #23780] DEBUG -- : ac45884e47e6: Pushed
D, [2017-05-19T15:35:53.235836 #23780] DEBUG -- : 7e0b138fec00: Pushed
D, [2017-05-19T15:36:04.332853 #23780] DEBUG -- : 0.1.0: digest: sha256:608557702901a6eb7403e2a5d86540877337df4051c93c4b58c452cd0aa3a8f0 size: 3470
D, [2017-05-19T15:36:04.848991 #23780] DEBUG -- : The push refers to a repository [gcr.io/gke-example-20170514/sample_app]
D, [2017-05-19T15:36:05.025439 #23780] DEBUG -- : 67f9fc3d4203: Preparing
D, [2017-05-19T15:36:05.025508 #23780] DEBUG -- : 07a3a0d30832: Preparing
D, [2017-05-19T15:36:05.025544 #23780] DEBUG -- : d6eac34e91b5: Preparing
D, [2017-05-19T15:36:05.025577 #23780] DEBUG -- : 3b20fdaa9c77: Preparing
D, [2017-05-19T15:36:05.025624 #23780] DEBUG -- : 7a668240bf6a: Preparing
D, [2017-05-19T15:36:05.025643 #23780] DEBUG -- : fd9c076fbb49: Preparing
D, [2017-05-19T15:36:05.025657 #23780] DEBUG -- : 07e51e3f80de: Preparing
D, [2017-05-19T15:36:05.025716 #23780] DEBUG -- : 8e6133f6d26b: Preparing
D, [2017-05-19T15:36:05.025732 #23780] DEBUG -- : fd8cb2d9bb24: Preparing
D, [2017-05-19T15:36:05.025746 #23780] DEBUG -- : 7e0b138fec00: Preparing
D, [2017-05-19T15:36:05.025760 #23780] DEBUG -- : ac45884e47e6: Preparing
D, [2017-05-19T15:36:05.025772 #23780] DEBUG -- : f078de0e3e2b: Preparing
D, [2017-05-19T15:36:05.025785 #23780] DEBUG -- : e6562eb04a92: Preparing
D, [2017-05-19T15:36:05.025800 #23780] DEBUG -- : 596280599f68: Preparing
D, [2017-05-19T15:36:05.025813 #23780] DEBUG -- : 5d6cbe0dbcf9: Preparing
D, [2017-05-19T15:36:05.025826 #23780] DEBUG -- : 07e51e3f80de: Waiting
D, [2017-05-19T15:36:05.025839 #23780] DEBUG -- : 8e6133f6d26b: Waiting
D, [2017-05-19T15:36:05.025854 #23780] DEBUG -- : fd8cb2d9bb24: Waiting
D, [2017-05-19T15:36:05.025871 #23780] DEBUG -- : 7e0b138fec00: Waiting
D, [2017-05-19T15:36:05.025884 #23780] DEBUG -- : ac45884e47e6: Waiting
D, [2017-05-19T15:36:05.025897 #23780] DEBUG -- : f078de0e3e2b: Waiting
D, [2017-05-19T15:36:05.025909 #23780] DEBUG -- : e6562eb04a92: Waiting
D, [2017-05-19T15:36:05.025925 #23780] DEBUG -- : 596280599f68: Waiting
D, [2017-05-19T15:36:05.025944 #23780] DEBUG -- : 5d6cbe0dbcf9: Waiting
D, [2017-05-19T15:36:05.025958 #23780] DEBUG -- : fd9c076fbb49: Waiting
D, [2017-05-19T15:36:06.802228 #23780] DEBUG -- : 07a3a0d30832: Layer already exists
D, [2017-05-19T15:36:06.824500 #23780] DEBUG -- : 67f9fc3d4203: Layer already exists
D, [2017-05-19T15:36:06.842831 #23780] DEBUG -- : d6eac34e91b5: Layer already exists
D, [2017-05-19T15:36:06.861312 #23780] DEBUG -- : 7a668240bf6a: Layer already exists
D, [2017-05-19T15:36:06.881298 #23780] DEBUG -- : 3b20fdaa9c77: Layer already exists
D, [2017-05-19T15:36:08.008966 #23780] DEBUG -- : 8e6133f6d26b: Layer already exists
D, [2017-05-19T15:36:08.034344 #23780] DEBUG -- : fd9c076fbb49: Layer already exists
D, [2017-05-19T15:36:08.057044 #23780] DEBUG -- : 7e0b138fec00: Layer already exists
D, [2017-05-19T15:36:08.079445 #23780] DEBUG -- : fd8cb2d9bb24: Layer already exists
D, [2017-05-19T15:36:08.141127 #23780] DEBUG -- : 07e51e3f80de: Layer already exists
D, [2017-05-19T15:36:08.498867 #23780] DEBUG -- : f078de0e3e2b: Layer already exists
D, [2017-05-19T15:36:08.562258 #23780] DEBUG -- : 596280599f68: Layer already exists
D, [2017-05-19T15:36:09.290600 #23780] DEBUG -- : ac45884e47e6: Layer already exists
D, [2017-05-19T15:36:09.312003 #23780] DEBUG -- : e6562eb04a92: Layer already exists
D, [2017-05-19T15:36:09.332676 #23780] DEBUG -- : 5d6cbe0dbcf9: Layer already exists
D, [2017-05-19T15:36:13.959379 #23780] DEBUG -- : latest: digest: sha256:608557702901a6eb7403e2a5d86540877337df4051c93c4b58c452cd0aa3a8f0 size: 3470
I, [2017-05-19T15:36:13.995329 #23780]  INFO -- : SUCCESS: docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:0.1.0 && docker tag sample_app:0.1.0 gcr.io/gke-example-20170514/sample_app:latest && gcloud docker -- push gcr.io/gke-example-20170514/sample_app:0.1.0 && gcloud docker -- push gcr.io/gke-example-20170514/sample_app:latest 2>&1
I, [2017-05-19T15:36:13.995401 #23780]  INFO -- : [docker push] OK
```
